// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDesktopConfig():Promise<Record<string, any>>;

export function OpenInbox():Promise<void>;

export function OpenLibrary():Promise<void>;

export function OpenPath(arg1:string):Promise<void>;
