// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDesktopConfig() {
  return window['go']['main']['DesktopApp']['GetDesktopConfig']();
}

export function OpenInbox() {
  return window['go']['main']['DesktopApp']['OpenInbox']();
}

export function OpenLibrary() {
  return window['go']['main']['DesktopApp']['OpenLibrary']();
}

export function OpenPath(arg1) {
  return window['go']['main']['DesktopApp']['OpenPath'](arg1);
}
